# --- CONFIGURAÇÕES GERAIS DA APLICAÇÃO ---
spring.application.name=backend
server.port=${SERVER_PORT:8080}

# --- CONFIGURAÇÕES BANCO DE DADOS ---
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:bank-app}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=org.postgresql.Driver

# --- CONFIGURAÇÕES JPA E HIBERNATE ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# --- CONFIGURAÇÕES JWT ---
api.security.token.secret=my-secret-key-from-project

# --- CONFIGURAÇÕES DE SEGURANÇA ---
spring.security.user.name=${SECURITY_USERNAME:admin}
spring.security.user.password=${SECURITY_PASSWORD:admin}


# --- CONFIGURAÇÕES DE LOG ---
logging.level.org.springframework.security=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# --- TRATAMENTO DE EXCEÇÕES ---
spring.web.resources.add-mappings=false

# --- CONFIGURAÇÕES DE SEGURANÇA ADICIONAIS ---
server.servlet.session.tracking-modes=cookie
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure=true

# --- OBSERVABILIDADE (Actuator & Prometheus) ---
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
management.prometheus.metrics.export.enabled=true